bluesea_node:
  ros__parameters:
  #ROS2#
    frame_id: rl_sensor
    scan_topic: /scan
    cloud_topic: cloud_rear
  #DATA#
    dev_id: -1
    hard_resample: false
    mask1: ''
    # max_angle: 2.094395
    # min_angle: -2.094395
    # min_angle: -3.1415926
    # max_angle: 3.1415926
    min_angle: -2.3561944902
    max_angle: 2.465
    max_dist: 50.0
    min_dist: 0.1
    output_360: true
    output_cloud2: false
    output_scan: true
    raw_bytes: 3
    reversed: true
    soft_resample: false
    with_angle_filter: true
  #CONNECT#
    group_ip: 224.1.2.3
    lidar_ip: 192.168.158.98
    lidar_port: 6543
    local_port: 6668
    type: udp
  #GET#
    uuid: -1
  #SET#
    alarm_msg: -1
    ats: -1
    direction: -1
    resample_res: -1.0
    rpm: -1
    with_confidence: -1
    with_deshadow: -1
    with_smooth: -1
  #NTP#
    ntp_enable: -1
    ntp_ip: 192.168.158.50
    ntp_port: 5678
  #QOS#
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
  #CUSTOM#
    error_circle: 3
    error_scale: 0.9
    group_listener: false
  #FITLER#
    filter_open: true
    filter_type: 1
    filter_window: 1
    max_range: 20.0
    max_range_difference: 0.1
    min_range: 0.5


  #OTHERS#
    from_zero: false
    inverted: false
    number: 1
    output_cloud: false
    start_type_description_service: true
    time_mode: 0
    unit_is_mm: -1
    use_sim_time: false